### ISSUE TITLE
How can I generate CHANGELOG.md when I first time bump version?

### ISSUE THREAD

**Issue by ModyQyW** [unjs/changelogen#75]
Hi. Thanks for your work.

When I try `changelogen`, I find no way to generate CHANGELOG.md when I first time bump version.

```shell
$ npx changelogen --release                    
Need to install the following packages:
  changelogen@0.5.1
Ok to proceed? (y) 

 ERROR  Command failed with exit code 128: git describe --tags --abbrev=0                                                                                                                                                                             16:07:45
fatal: No tags can describe 'dbd9fa593d64f0a04bb801be556eae775242c48a'.
Try --always, or create some tags.

  fatal: No tags can describe 'dbd9fa593d64f0a04bb801be556eae775242c48a'.
  Try --always, or create some tags.
  at makeError (/Users/wurui/.npm/_npx/fd5a125c5466fd2f/node_modules/execa/lib/error.js:59:11)
  at handlePromise (/Users/wurui/.npm/_npx/fd5a125c5466fd2f/node_modules/execa/index.js:124:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async execCommand (/Users/wurui/.npm/_npx/fd5a125c5466fd2f/node_modules/changelogen/dist/shared/changelogen.53701f80.mjs:94:15)
  at async getLastGitTag (/Users/wurui/.npm/_npx/fd5a125c5466fd2f/node_modules/changelogen/dist/shared/changelogen.53701f80.mjs:13:13)
  at async loadChangelogConfig (/Users/wurui/.npm/_npx/fd5a125c5466fd2f/node_modules/changelogen/dist/shared/changelogen.53701f80.mjs:415:19)
  at async Module.defaultMain (/Users/wurui/.npm/_npx/fd5a125c5466fd2f/node_modules/changelogen/dist/chunks/default.mjs:24:18)
  at async main (/Users/wurui/.npm/_npx/fd5a125c5466fd2f/node_modules/changelogen/dist/cli.mjs:22:3)
```

Can you please give me some advice? Thanks.

**Comment by devonik** [comment]
Hey i had the same. The tool is looking for a git tag to have start for changelog.md.
Just do git tag 0.0.1 && git push --tags. After that it should work

**Comment by ModyQyW** [comment]
Thanks for your advice. I am also waiting https://github.com/unjs/changelogen/pull/77 release.
